apiVersion: v1
kind: Service
metadata:
  name: ably-backend-lb
  namespace: my-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:098150418900:certificate/a30ecb2f-7bbe-4a31-8090-9729a6f2d300"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: ably-backend
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
