apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ably-secret
  namespace: my-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ably-api-secret
    creationPolicy: Owner
  data:
    - secretKey: Ably__ApiKey
      remoteRef:
        key: ably-api-key
        property: Ably.ApiKey
